resolver: lts-18.18
packages:
- '.'

extra-deps:
- unicode-data-0.3.0
- git: https://github.com/composewell/streamly
  commit: "cbccb7777792cb4bf8dd8716929f4e28ea6cf718"
- git: https://github.com/composewell/streamly
  commit: "cbccb7777792cb4bf8dd8716929f4e28ea6cf718"
  subdirs:
    - core
- git: https://github.com/composewell/streamly-process
  commit: "e8aef97965f3d89bb1d4e50564b69572db2e8a8a"
